### ISSUE TITLE
Running exe from file explorer and powershell throws exception

### ISSUE THREAD

**Issue by inkydom** [TASagent/TASagentTwitchBotDemos#1]
I built a release version of the NoOverlaysDemo project. I navigated to: `C:\Users\dom\Documents\TASagentTwitchBotDemos\TASagentTwitchBot.NoOverlaysDemo\bin\Release\net6.0-windows` and double clicked on `TASagentTwitchBot.NoOverlaysDemo.exe` to run. The program seems to start and immediately exit. 

I launched powershell and ran the program and this was the exception I got:

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at TASagentTwitchBot.Core.Extensions.StartupUtilities.UseCoreLibraryContent(WebApplication app, String libraryName, Boolean useDefault) in C:\Users\dom\Documents\TASagentTwitchBotDemos\TASagentTwitchBotCore\TASagentTwitchBot.Core\Extensions\StartupUtilities.cs:line 31
   at Program.<Main>$(String[] args) in C:\Users\dom\Documents\TASagentTwitchBotDemos\TASagentTwitchBot.NoOverlaysDemo\Program.cs:line 172
   at Program.<Main>(String[] args)
```

The line in question is:

`wwwRootPath = Path.Combine(app.Environment.WebRootPath, "_content", libraryName);`

How are you running this without visual studio (if you are). Any suggestions on how to resolve this? I tried running from the solution, project, and bin directories in case it was a pathing issue.

I should note I can run it fine from within visual studio hitting f5.

Thanks

**Comment by inkydom** [comment]
A thought just occured to me it could be an environment variable issue if VS sets it before running. So I found the environment variables and ran in powershell:

`$Env:ASPNETCORE_ENVIRONMENT="Development"`

Then running: `$Env:ASPNETCORE_ENVIRONMENT` in powershell confirmed it was set to: `Development`

Unfortunately this didn't change the error.

**Comment by tstavropoulos** [comment]
Try, instead of running the build executable, using "Publish" and publishing it to a directory. That executable you should be able to run directly. When it's published to a directory the required commandline arguments are packaged into the build. Let me know if that works for you.

**Comment by TASagent** [comment]
Try, instead of running the build executable, using "Publish" and publishing it to a directory. That executable you should be able to run directly. When it's published to a directory the required commandline arguments are packaged into the build. Let me know if that works for you.

**Comment by inkydom** [comment]
Unfortunately I'm still getting the same error after publishing. I can just run in the VS so it's not a big problem. This is my publish configuration: 
![image](https://user-images.githubusercontent.com/83842356/149611675-7777258e-84d6-4942-909d-726b49a8e1dc.png)

I am publishing to a folder if it isn't clear. The error I'm getting is:

```
Unhandled exception. System.IO.DirectoryNotFoundException: C:\Users\dom\Documents\TASagentTwitchBotDemos\TASagentTwitchBot.NoOverlaysDemo\bin\Release\net6.0-windows\publish\wwwroot\_content\TASagentTwitchBot.Plugin.ControllerSpy\
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at TASagentTwitchBot.Core.Extensions.StartupUtilities.UseCoreLibraryContent(WebApplication app, String libraryName, Boolean useDefault) in C:\Users\dom\Documents\TASagentTwitchBotDemos\TASagentTwitchBotCore\TASagentTwitchBot.Core\Extensions\StartupUtilities.cs:line 34
   at Program.<Main>$(String[] args) in C:\Users\dom\Documents\TASagentTwitchBotDemos\TASagentTwitchBot.NoOverlaysDemo\Program.cs:line 175
   at Program.<Main>(String[] args)
```
I wasn't quite sure why that line was having issues, it looks like something about copying over the project/build files. I commented it out to see how how it would do. I got the same error but for the TTAS project, so I comment that out. Below is the error I then got, which at first glance would seem I have another project on port 5000, but I confirmed the project still runs fine from visual studio and restarted then pinged localhost:5000 to confirm nothing is on it, same error.

```
 .\TASagentTwitchBot.NoOverlaysDemo.exe
Unhandled exception. System.IO.IOException: Failed to bind to address http://0.0.0.0:5000: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Only one usage of each socket address (protocol/network address/port) is normally permitted.
 ---> System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\dom\Documents\TASagentTwitchBotDemos\TASagentTwitchBot.NoOverlaysDemo\Program.cs:line 189
   at Program.<Main>(String[] args)
```

**Comment by TASagent** [comment]
Thanks Dom!

When looking into the issue, I realized that I made an obvious oversight when migrating to the new format.  It took me a minute, and then I realized "_Of course_ NoOverlaysDemo can't be using Text-To-TAS or the Controller overlay - those require overlays" 🤦 . Those errors were genuine, and those lines should be deleted. Now, as for the `Failed to bind` error, that's different beast I need to look into. I'm guessing that one is unrelated.
